/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hiraganatest;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author brand
 */
public class Hiragana extends javax.swing.JFrame {

    /**
     * Creates new form Hiragana
     */
    public Hiragana() {
        initComponents();
        lblPicture.setIcon(new ImageIcon("Hirigana/girl.jpg"));

    }

    public void setChar(){
        n = rand.nextInt(46);
        character = chars1[n];
        
        lblHirigana.setIcon(new ImageIcon(character));
        txtCorrect.setText("");

    }
    public void checkAnswer(String Answer){
        answered++;
        String lbl = lblHirigana.getIcon().toString();
        if (lbl.equals(Answer)) {
            
            txtCorrect.setText("Correct!");
            setChar();
            correct++;
            
            
            
        }else{
            txtCorrect.setText("Incorrect");
            incorrect++;
        }
        
    }
    
    Random rand = new Random();
    String answer;
    int correct = 0;
    int incorrect = 0;
    int answered = 0;
    int  n;
    String A = "Hirigana/hirigana_a.png";
    String I = "Hirigana/hirigana_i.png";
    String U = "Hirigana/hirigana_u.png";
    String E = "Hirigana/hirigana_e.png";
    String O = "Hirigana/hirigana_o.png";
    
    String Ka = "Hirigana/hirigana_ka.png";
    String Ki = "Hirigana/hirigana_ki.png";
    String Ku = "Hirigana/hirigana_ku.png";
    String Ke = "Hirigana/hirigana_ke.png";
    String Ko = "Hirigana/hirigana_ko.png";
    
    String Sa = "Hirigana/hirigana_sa.png";
    String Shi = "Hirigana/hirigana_shi.png";
    String Su = "Hirigana/hirigana_su.png";
    String Se = "Hirigana/hirigana_se.png";
    String So = "Hirigana/hirigana_so.png";
    
    String Ta = "Hirigana/hirigana_ta.png";
    String Chi = "Hirigana/hirigana_chi.png";
    String Tsu = "Hirigana/hirigana_tsu.png";
    String Te = "Hirigana/hirigana_te.png";
    String To = "Hirigana/hirigana_to.png";
    
    String Na = "Hirigana/hirigana_na.png";
    String Ni = "Hirigana/hirigana_ni.png";
    String Nu = "Hirigana/hirigana_nu.png";
    String Ne = "Hirigana/hirigana_ne.png";
    String No = "Hirigana/hirigana_no.png";
    
    String Ha = "Hirigana/hirigana_ha.png";
    String Hi = "Hirigana/hirigana_hi.png";
    String Fu = "Hirigana/hirigana_fu.png";
    String He = "Hirigana/hirigana_he.png";
    String Ho = "Hirigana/hirigana_ho.png";
    
    String Ma = "Hirigana/hirigana_ma.png";
    String Mi = "Hirigana/hirigana_mi.png";
    String Mu = "Hirigana/hirigana_mu.png";
    String Me = "Hirigana/hirigana_me.png";
    String Mo = "Hirigana/hirigana_mo.png";
    
    String Ya = "Hirigana/hirigana_ya.png";
    String Yu = "Hirigana/hirigana_yu.png";
    String Yo = "Hirigana/hirigana_yo.png";
    
    String Ra = "Hirigana/hirigana_ra.png";
    String Ri = "Hirigana/hirigana_ri.png";
    String Ru = "Hirigana/hirigana_ru.png";
    String Re = "Hirigana/hirigana_re.png";
    String Ro = "Hirigana/hirigana_ro.png";
    
    String Wa = "Hirigana/hirigana_wa.png";
    String N = "Hirigana/hirigana_n.png";
    String Wo = "Hirigana/hirigana_wo.png";
    

    
    
    
    
    String[] chars1 = {A,I,U,E,O,Ka,Ki,Ku,Ke,Ko,Sa,Shi,Su,Se,So,Ta,Chi,Tsu,Te,To,Na,Ni,Nu,Ne,No,Ha,Hi,Fu,He,Ho,Ma,Mi,Mu,Me,Mo,Ya,Yu,Yo,Ra,Ri,Ru,Re,Ro,Wa,N,Wo};
    String character;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHirigana = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnKA = new javax.swing.JButton();
        btnKI = new javax.swing.JButton();
        btnKU = new javax.swing.JButton();
        btnKE = new javax.swing.JButton();
        btnKO = new javax.swing.JButton();
        btnSA = new javax.swing.JButton();
        btnSHI = new javax.swing.JButton();
        btnSU = new javax.swing.JButton();
        btnSE = new javax.swing.JButton();
        btnSO = new javax.swing.JButton();
        btnTA = new javax.swing.JButton();
        btnCHI = new javax.swing.JButton();
        btnTSU = new javax.swing.JButton();
        btnTE = new javax.swing.JButton();
        btnTO = new javax.swing.JButton();
        btnNA = new javax.swing.JButton();
        btnNI = new javax.swing.JButton();
        btnNU = new javax.swing.JButton();
        btnNE = new javax.swing.JButton();
        btnNO = new javax.swing.JButton();
        btnHA = new javax.swing.JButton();
        btnHI = new javax.swing.JButton();
        btnFU = new javax.swing.JButton();
        btnHE = new javax.swing.JButton();
        btnHO = new javax.swing.JButton();
        btnMA = new javax.swing.JButton();
        btnMI = new javax.swing.JButton();
        btnMU = new javax.swing.JButton();
        btnME = new javax.swing.JButton();
        btnMO = new javax.swing.JButton();
        btnYO = new javax.swing.JButton();
        btnYU = new javax.swing.JButton();
        btnYA = new javax.swing.JButton();
        btnRO = new javax.swing.JButton();
        btnRE = new javax.swing.JButton();
        btnRA = new javax.swing.JButton();
        btnRI = new javax.swing.JButton();
        btnRU = new javax.swing.JButton();
        btnWO = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnWA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCorrect = new javax.swing.JTextArea();
        lblPicture = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hiragana");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblHirigana.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblHirigana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHirigana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnStart.setText(" スタート/ Start!");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnI.setText("I");
        btnI.setPreferredSize(new java.awt.Dimension(50, 50));
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });

        btnU.setText("U");
        btnU.setPreferredSize(new java.awt.Dimension(50, 50));
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        btnA.setText("A");
        btnA.setPreferredSize(new java.awt.Dimension(50, 50));
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnE.setText("E");
        btnE.setPreferredSize(new java.awt.Dimension(50, 50));
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnO.setText("O");
        btnO.setPreferredSize(new java.awt.Dimension(50, 50));
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });

        btnKA.setText("KA");
        btnKA.setPreferredSize(new java.awt.Dimension(50, 50));
        btnKA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKAActionPerformed(evt);
            }
        });

        btnKI.setText("KI");
        btnKI.setPreferredSize(new java.awt.Dimension(50, 50));
        btnKI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKIActionPerformed(evt);
            }
        });

        btnKU.setText("KU");
        btnKU.setPreferredSize(new java.awt.Dimension(50, 50));
        btnKU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKUActionPerformed(evt);
            }
        });

        btnKE.setText("KE");
        btnKE.setPreferredSize(new java.awt.Dimension(50, 50));
        btnKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKEActionPerformed(evt);
            }
        });

        btnKO.setText("KO");
        btnKO.setPreferredSize(new java.awt.Dimension(50, 50));
        btnKO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKOActionPerformed(evt);
            }
        });

        btnSA.setText("SA");
        btnSA.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAActionPerformed(evt);
            }
        });

        btnSHI.setText("SHI");
        btnSHI.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSHI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSHIActionPerformed(evt);
            }
        });

        btnSU.setText("SU");
        btnSU.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUActionPerformed(evt);
            }
        });

        btnSE.setText("SE");
        btnSE.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEActionPerformed(evt);
            }
        });

        btnSO.setText("SO");
        btnSO.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSOActionPerformed(evt);
            }
        });

        btnTA.setText("TA");
        btnTA.setPreferredSize(new java.awt.Dimension(50, 50));
        btnTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTAActionPerformed(evt);
            }
        });

        btnCHI.setText("CHI");
        btnCHI.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCHI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCHIActionPerformed(evt);
            }
        });

        btnTSU.setText("TSU");
        btnTSU.setPreferredSize(new java.awt.Dimension(50, 50));
        btnTSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTSUActionPerformed(evt);
            }
        });

        btnTE.setText("TE");
        btnTE.setPreferredSize(new java.awt.Dimension(50, 50));
        btnTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTEActionPerformed(evt);
            }
        });

        btnTO.setText("TO");
        btnTO.setPreferredSize(new java.awt.Dimension(50, 50));
        btnTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTOActionPerformed(evt);
            }
        });

        btnNA.setText("NA");
        btnNA.setPreferredSize(new java.awt.Dimension(50, 50));
        btnNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNAActionPerformed(evt);
            }
        });

        btnNI.setText("NI");
        btnNI.setPreferredSize(new java.awt.Dimension(50, 50));
        btnNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNIActionPerformed(evt);
            }
        });

        btnNU.setText("NU");
        btnNU.setPreferredSize(new java.awt.Dimension(50, 50));
        btnNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNUActionPerformed(evt);
            }
        });

        btnNE.setText("NE");
        btnNE.setPreferredSize(new java.awt.Dimension(50, 50));
        btnNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNEActionPerformed(evt);
            }
        });

        btnNO.setText("NO");
        btnNO.setPreferredSize(new java.awt.Dimension(50, 50));
        btnNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNOActionPerformed(evt);
            }
        });

        btnHA.setText("HA");
        btnHA.setPreferredSize(new java.awt.Dimension(50, 50));
        btnHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAActionPerformed(evt);
            }
        });

        btnHI.setText("HI");
        btnHI.setPreferredSize(new java.awt.Dimension(50, 50));
        btnHI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHIActionPerformed(evt);
            }
        });

        btnFU.setText("FU");
        btnFU.setPreferredSize(new java.awt.Dimension(50, 50));
        btnFU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFUActionPerformed(evt);
            }
        });

        btnHE.setText("HE");
        btnHE.setPreferredSize(new java.awt.Dimension(50, 50));
        btnHE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHEActionPerformed(evt);
            }
        });

        btnHO.setText("HO");
        btnHO.setPreferredSize(new java.awt.Dimension(50, 50));
        btnHO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHOActionPerformed(evt);
            }
        });

        btnMA.setText("MA");
        btnMA.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAActionPerformed(evt);
            }
        });

        btnMI.setText("MI");
        btnMI.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMIActionPerformed(evt);
            }
        });

        btnMU.setText("MU");
        btnMU.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUActionPerformed(evt);
            }
        });

        btnME.setText("ME");
        btnME.setPreferredSize(new java.awt.Dimension(50, 50));
        btnME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEActionPerformed(evt);
            }
        });

        btnMO.setText("MO");
        btnMO.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMOActionPerformed(evt);
            }
        });

        btnYO.setText("YO");
        btnYO.setPreferredSize(new java.awt.Dimension(50, 50));
        btnYO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYOActionPerformed(evt);
            }
        });

        btnYU.setText("YU");
        btnYU.setPreferredSize(new java.awt.Dimension(50, 50));
        btnYU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYUActionPerformed(evt);
            }
        });

        btnYA.setText("YA");
        btnYA.setPreferredSize(new java.awt.Dimension(50, 50));
        btnYA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYAActionPerformed(evt);
            }
        });

        btnRO.setText("RO");
        btnRO.setPreferredSize(new java.awt.Dimension(50, 50));
        btnRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnROActionPerformed(evt);
            }
        });

        btnRE.setText("RE");
        btnRE.setPreferredSize(new java.awt.Dimension(50, 50));
        btnRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREActionPerformed(evt);
            }
        });

        btnRA.setText("RA");
        btnRA.setPreferredSize(new java.awt.Dimension(50, 50));
        btnRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAActionPerformed(evt);
            }
        });

        btnRI.setText("RI");
        btnRI.setPreferredSize(new java.awt.Dimension(50, 50));
        btnRI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRIActionPerformed(evt);
            }
        });

        btnRU.setText("RU");
        btnRU.setPreferredSize(new java.awt.Dimension(50, 50));
        btnRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRUActionPerformed(evt);
            }
        });

        btnWO.setText("WO");
        btnWO.setPreferredSize(new java.awt.Dimension(50, 50));
        btnWO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWOActionPerformed(evt);
            }
        });

        btnN.setText("N");
        btnN.setPreferredSize(new java.awt.Dimension(50, 50));
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });

        btnWA.setText("WA");
        btnWA.setPreferredSize(new java.awt.Dimension(50, 50));
        btnWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWAActionPerformed(evt);
            }
        });

        txtCorrect.setColumns(1);
        txtCorrect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCorrect.setRows(1);
        txtCorrect.setAutoscrolls(false);
        txtCorrect.setEnabled(false);
        jScrollPane1.setViewportView(txtCorrect);

        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSeparator1.setBackground(new java.awt.Color(153, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(153, 204, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setEnabled(false);

        jSeparator2.setBackground(new java.awt.Color(153, 204, 255));
        jSeparator2.setForeground(new java.awt.Color(153, 204, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHirigana, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnWA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRU, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnRE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnWO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnHA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnHI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnFU, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnHE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnHO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnKA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCHI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnKI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSHI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNU, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTSU, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnKU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnTE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnKE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnKO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnMA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnMI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnMU, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnME, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnMO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnYA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnYU, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnYO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSHI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTSU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCHI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnME, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnYU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnYA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnYO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHirigana, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStart)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        setChar();
        btnStart.setVisible(false);
        
        //btnStart.setVisible(false);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
        checkAnswer(A);
    }//GEN-LAST:event_btnAActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
        // TODO add your handling code here:
        checkAnswer(I);       
    }//GEN-LAST:event_btnIActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        // TODO add your handling code here:
        checkAnswer(U);
    }//GEN-LAST:event_btnUActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
        checkAnswer(E);
    }//GEN-LAST:event_btnEActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        // TODO add your handling code here:
        checkAnswer(O);
    }//GEN-LAST:event_btnOActionPerformed

    private void btnKAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKAActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ka); 
    }//GEN-LAST:event_btnKAActionPerformed

    private void btnKIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKIActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ki); 
    }//GEN-LAST:event_btnKIActionPerformed

    private void btnKUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKUActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ku); 
    }//GEN-LAST:event_btnKUActionPerformed

    private void btnKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKEActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ke);
    }//GEN-LAST:event_btnKEActionPerformed

    private void btnKOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKOActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ko);
    }//GEN-LAST:event_btnKOActionPerformed

    private void btnSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAActionPerformed
        // TODO add your handling code here:
        checkAnswer(Sa);
    }//GEN-LAST:event_btnSAActionPerformed

    private void btnSHIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSHIActionPerformed
        // TODO add your handling code here:
        checkAnswer(Shi);
    }//GEN-LAST:event_btnSHIActionPerformed

    private void btnSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUActionPerformed
        // TODO add your handling code here:
        checkAnswer(Su);
    }//GEN-LAST:event_btnSUActionPerformed

    private void btnSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEActionPerformed
        // TODO add your handling code here:
        checkAnswer(Se);
    }//GEN-LAST:event_btnSEActionPerformed

    private void btnSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSOActionPerformed
        // TODO add your handling code here:
        checkAnswer(So);
    }//GEN-LAST:event_btnSOActionPerformed

    private void btnTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTAActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ta);
    }//GEN-LAST:event_btnTAActionPerformed

    private void btnCHIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCHIActionPerformed
        // TODO add your handling code here:
        checkAnswer(Chi);
    }//GEN-LAST:event_btnCHIActionPerformed

    private void btnTSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTSUActionPerformed
        // TODO add your handling code here:
        checkAnswer(Tsu);
    }//GEN-LAST:event_btnTSUActionPerformed

    private void btnTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTEActionPerformed
        // TODO add your handling code here:
        checkAnswer(Te);
    }//GEN-LAST:event_btnTEActionPerformed

    private void btnTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTOActionPerformed
        // TODO add your handling code here:
        checkAnswer(To);
    }//GEN-LAST:event_btnTOActionPerformed

    private void btnNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNAActionPerformed
        // TODO add your handling code here:
        checkAnswer(Na);
    }//GEN-LAST:event_btnNAActionPerformed

    private void btnNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNIActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ni);
    }//GEN-LAST:event_btnNIActionPerformed

    private void btnNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNUActionPerformed
        // TODO add your handling code here:
        checkAnswer(Nu);
    }//GEN-LAST:event_btnNUActionPerformed

    private void btnNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNEActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ne);
    }//GEN-LAST:event_btnNEActionPerformed

    private void btnNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNOActionPerformed
        // TODO add your handling code here:
        checkAnswer(No);
    }//GEN-LAST:event_btnNOActionPerformed

    private void btnHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ha);
    }//GEN-LAST:event_btnHAActionPerformed

    private void btnHIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHIActionPerformed
        // TODO add your handling code here:
        checkAnswer(Hi);
    }//GEN-LAST:event_btnHIActionPerformed

    private void btnFUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFUActionPerformed
        // TODO add your handling code here:
        checkAnswer(Fu);
    }//GEN-LAST:event_btnFUActionPerformed

    private void btnHEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHEActionPerformed
        // TODO add your handling code here:
        checkAnswer(He);
    }//GEN-LAST:event_btnHEActionPerformed

    private void btnHOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHOActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ho);
    }//GEN-LAST:event_btnHOActionPerformed

    private void btnMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ma);
    }//GEN-LAST:event_btnMAActionPerformed

    private void btnMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMIActionPerformed
        // TODO add your handling code here:
        checkAnswer(Mi);
    }//GEN-LAST:event_btnMIActionPerformed

    private void btnMUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUActionPerformed
        // TODO add your handling code here:
        checkAnswer(Mu);
    }//GEN-LAST:event_btnMUActionPerformed

    private void btnMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEActionPerformed
        // TODO add your handling code here:
        checkAnswer(Me);
    }//GEN-LAST:event_btnMEActionPerformed

    private void btnMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMOActionPerformed
        // TODO add your handling code here:
        checkAnswer(Mo);
    }//GEN-LAST:event_btnMOActionPerformed

    private void btnYOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYOActionPerformed
        // TODO add your handling code here:
        checkAnswer(Yo);
    }//GEN-LAST:event_btnYOActionPerformed

    private void btnYUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYUActionPerformed
        // TODO add your handling code here:
        checkAnswer(Yu);
    }//GEN-LAST:event_btnYUActionPerformed

    private void btnYAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYAActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ya);
    }//GEN-LAST:event_btnYAActionPerformed

    private void btnRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ra);
    }//GEN-LAST:event_btnRAActionPerformed

    private void btnRIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRIActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ri);
    }//GEN-LAST:event_btnRIActionPerformed

    private void btnRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRUActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ru);
    }//GEN-LAST:event_btnRUActionPerformed

    private void btnREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREActionPerformed
        // TODO add your handling code here:
        checkAnswer(Re);
    }//GEN-LAST:event_btnREActionPerformed

    private void btnROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnROActionPerformed
        // TODO add your handling code here:
        checkAnswer(Ro);
    }//GEN-LAST:event_btnROActionPerformed

    private void btnWOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWOActionPerformed
        // TODO add your handling code here:
        checkAnswer(Wo);
    }//GEN-LAST:event_btnWOActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        // TODO add your handling code here:
        checkAnswer(N);
    }//GEN-LAST:event_btnNActionPerformed

    private void btnWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWAActionPerformed
        // TODO add your handling code here:
        checkAnswer(Wa);
    }//GEN-LAST:event_btnWAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hiragana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Hiragana().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnCHI;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnFU;
    private javax.swing.JButton btnHA;
    private javax.swing.JButton btnHE;
    private javax.swing.JButton btnHI;
    private javax.swing.JButton btnHO;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnKA;
    private javax.swing.JButton btnKE;
    private javax.swing.JButton btnKI;
    private javax.swing.JButton btnKO;
    private javax.swing.JButton btnKU;
    private javax.swing.JButton btnMA;
    private javax.swing.JButton btnME;
    private javax.swing.JButton btnMI;
    private javax.swing.JButton btnMO;
    private javax.swing.JButton btnMU;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnNA;
    private javax.swing.JButton btnNE;
    private javax.swing.JButton btnNI;
    private javax.swing.JButton btnNO;
    private javax.swing.JButton btnNU;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnRA;
    private javax.swing.JButton btnRE;
    private javax.swing.JButton btnRI;
    private javax.swing.JButton btnRO;
    private javax.swing.JButton btnRU;
    private javax.swing.JButton btnSA;
    private javax.swing.JButton btnSE;
    private javax.swing.JButton btnSHI;
    private javax.swing.JButton btnSO;
    private javax.swing.JButton btnSU;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnTA;
    private javax.swing.JButton btnTE;
    private javax.swing.JButton btnTO;
    private javax.swing.JButton btnTSU;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnWA;
    private javax.swing.JButton btnWO;
    private javax.swing.JButton btnYA;
    private javax.swing.JButton btnYO;
    private javax.swing.JButton btnYU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblHirigana;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JTextArea txtCorrect;
    // End of variables declaration//GEN-END:variables
}
